window.translations = {
    en: {
        backHome: "← Back to Home",
        catNouns: "Nouns & Words", catVerbs: "Verbs", catStructure: "Structure",
        topicArticles: "Articles (a, an, the)", topicPlurals: "Plural Nouns", topicPreps: "Prepositions (in, on, at)", topicModals: "Modal Verbs", topicPassive: "Passive Voice", topicCond: "Conditionals",
        comingSoon: "Content coming soon...",
        artTitle: "Articles", artIntro: "Master the use of A, AN, and THE in English.",
        artCard1Title: "🔸 1. A / AN (Indefinite Articles)",
        artCard1Desc: "👉 Used when we talk about something <b>general</b> or for the <b>first time</b>.",
        artADesc: "Used before words that start with a <b>consonant</b> sound.",
        artAnDesc: "Used before words that start with a <b>vowel</b> sound.",
        exTitle: "📌 <b>Examples:</b>", exTitle2: "📌 <b>Examples:</b>", exTitle3: "📌 <b>Examples:</b>",
        artEx1: "I have <b>a</b> dog.", artEx2: "She bought <b>an</b> umbrella.",
        artCard2Title: "🔸 2. THE (Definite Article)",
        artCard2Desc: "👉 Used when something is <b>specific</b> or already known to the listener.",
        artEx3: "I saw a dog. <b>The</b> dog was big.", artEx4: "Close <b>the</b> door.",
        artWhenThe: "🔸 When we also use THE:",
        artUnique: "✔️ Unique things", artGeo: "✔️ Geography", artSuper: "✔️ Superlatives",
        artCard3Title: "🔸 3. No Article (Zero Article)",
        artCard3Desc: "👉 Used when speaking in general about plural nouns or uncountable things.",
        artEx5: "I like music.", artEx6: "Dogs are friendly.", artEx7: "She goes to school.",
        artSumTitle: "🔥 Quick Summary",
        artSum1: "<b>a / an</b> → something general", artSum2: "<b>the</b> → something specific", artSum3: "<b>no article</b> → general ideas or plural/uncountable nouns",
        // --- PLURAL NOUNS ---
        plTitle: "Plural Nouns", 
        plIntro: "Plural nouns are used when we talk about more than one thing.",
        plR1Title: "🔸 1. Regular Plurals (add -s)", plR1Desc: "👉 Most nouns just add <b>-s</b>.",
        plR2Title: "🔸 2. Nouns ending in -s, -sh, -ch, -x, -z", plR2Desc: "👉 Add <b>-es</b> to make pronunciation easier.",
        plR3Title: "🔸 3. Nouns ending in -y", 
        plR3C1: "✔️ Consonant + Y", plR3C1Desc: "Change -y to <b>-ies</b>.", 
        plR3C2: "✔️ Vowel + Y", plR3C2Desc: "Just add <b>-s</b>.",
        plR4Title: "🔸 4. Nouns ending in -f / -fe", plR4Desc: "👉 Often change to <b>-ves</b>.", plR4Exc: "⚠️ Exceptions:",
        plR5Title: "🔸 5. Irregular Plurals (must memorize)", plR5Desc: "👉 These don’t follow rules.",
        plR6Title: "🔸 6. Same in singular & plural",
        exTitle4: "📌 <b>Examples:</b>", exTitle5: "📌 <b>Examples:</b>",
        plSumTitle: "🔥 Quick Summary",
        plSum1: "<b>add -s</b> → most words", plSum2: "<b>add -es</b> → after s, sh, ch, x, z", 
        plSum3: "<b>-y</b> → -ies (if consonant before)", plSum4: "<b>-f</b> → -ves (sometimes)", plSum5: "<b>irregular</b> → learn by heart",
        // --- PREPOSITIONS ---
        prepTitle: "Prepositions: in, on, at",
        prepIntro: "These prepositions are used for time and place, and they can be confusing — but there’s a simple logic 👇",
        prepR1Title: "🔸 1. IN", prepR1Desc: "👉 Used for <b>longer periods</b> of time and <b>inside</b> spaces.",
        prepTime: "⏰ Time:", prepPlaceIn: "📍 Place (inside something):",
        prepInEx1: "I was born <b>in</b> 2008.", prepInEx2: "She is <b>in</b> the room.",
        prepR2Title: "🔸 2. ON", prepR2Desc: "👉 Used for <b>days / dates</b> and <b>surfaces</b>.",
        prepPlaceOn: "📍 Place (on a surface):",
        prepOnEx1: "I have a test <b>on</b> Monday.", prepOnEx2: "The phone is <b>on</b> the table.",
        prepR3Title: "🔸 3. AT", prepR3Desc: "👉 Used for <b>exact times</b> and <b>specific places</b>.",
        prepPlaceAt: "📍 Place (point/location):",
        prepAtEx1: "I wake up <b>at</b> 7 AM.", prepAtEx2: "She is <b>at</b> the station.",
        prepCompTitle: "🔥 Quick Comparison",
        prepTh1: "Preposition", prepTh2: "Time", prepTh3: "Place",
        prepTd1: "months, years", prepTd2: "inside something",
        prepTd3: "days, dates", prepTd4: "on a surface",
        prepTd5: "exact time", prepTd6: "specific point",
        prepMistakesTitle: "⚠️ Common Mistakes:",
        // --- MODAL VERBS ---
        modTitle: "Modal Verbs",
        modIntro: "Modal verbs are special verbs used to express ability, possibility, permission, obligation, advice, etc.",
        modCommonTitle: "🔸 Common Modal Verbs",
        modR1Title: "🔸 1. CAN / COULD", modR1Desc: "👉 Ability / possibility / permission",
        modR1Ex1: "I <b>can</b> swim. (ability)", modR1Ex2: "<b>Can</b> I go out? (permission)", modR1Ex3: "It <b>could</b> rain. (possibility)",
        modR2Title: "🔸 2. MAY / MIGHT", modR2Desc: "👉 Possibility (more formal / less certain)",
        modR2Ex1: "It <b>may</b> rain.", modR2Ex2: "She <b>might</b> come later.",
        modR3Title: "🔸 3. MUST / HAVE TO", modR3Desc: "👉 Obligation / necessity",
        modR3Ex1: "You <b>must</b> study. (strong / personal)", modR3Ex2: "I <b>have to</b> wake up early. (rule / situation)",
        modR4Title: "🔸 4. SHOULD", modR4Desc: "👉 Advice / recommendation",
        modR4Ex1: "You <b>should</b> sleep more.", modR4Ex2: "He <b>should</b> apologize.",
        modR5Title: "🔸 5. WILL / WOULD", modR5Desc: "👉 Future / polite requests / conditionals",
        modR5Ex1: "I <b>will</b> call you.", modR5Ex2: "<b>Would</b> you help me?", modR5Ex3: "I <b>would</b> go if I had time.",
        modRulesTitle: "🔥 Important Rules",
        modRule1: "✔️ <b>1. No “to” after modal verbs</b>",
        modRule2: "✔️ <b>2. Base form of verb</b>",
        modRule3: "✔️ <b>3. No -s in 3rd person</b>",
        modSumTitle: "🔥 Quick Summary",
        modSum1: "<b style='width: 150px;'>can</b> → ability",
        modSum2: "<b style='width: 150px;'>could / might / may</b> → possibility",
        modSum3: "<b style='width: 150px;'>must / have to</b> → obligation",
        modSum4: "<b style='width: 150px;'>should</b> → advice",
        modSum5: "<b style='width: 150px;'>will / would</b> → future / polite",
        // --- PASSIVE VOICE ---
        pasTitle: "Passive Voice",
        pasIntro: "The passive voice is used when the action is more important than the person who does it, or the doer is unknown.",
        pasR1Title: "🔸 Structure", pasR1Desc: "👉 <b>be</b> (in correct tense) + <b>past participle (V3)</b>",
        pasR1Ex1: "Active: She writes a letter", pasR1Ex2: "Passive: A letter <b>is written</b> (by her)",
        pasR2Title: "🔸 When to use Passive Voice",
        pasUse1: "✔️ 1. Doer is unknown", pasUse1Ex: "My phone <b>was stolen</b>",
        pasUse2: "✔️ 2. Doer is not important", pasUse2Ex: "The road <b>is being repaired</b>",
        pasUse3: "✔️ 3. Formal / scientific style", pasUse3Ex: "The experiment <b>was conducted</b>",
        pasR3Title: "🔸 Passive in Different Tenses",
        pasT1A: "Active: They make cars", pasT1P: "Passive: Cars <b>are made</b>",
        pasT2A: "Active: They built a house", pasT2P: "Passive: A house <b>was built</b>",
        pasT3A: "Active: They will finish the work", pasT3P: "Passive: The work <b>will be finished</b>",
        pasT4A: "Active: They are building a bridge", pasT4P: "Passive: A bridge <b>is being built</b>",
        pasT5A: "Active: They have cleaned the room", pasT5P: "Passive: The room <b>has been cleaned</b>",
        pasR4Title: "🔸 By + Doer", pasR4Desc: "👉 Use <b>by</b> if we want to say who did the action.",
        pasR4Ex1: "The book was written <b>by him</b>", pasR4Ex2: "The song was sung <b>by her</b>",
        pasRulesTitle: "🔥 Important Rules",
        pasRule1: "✔️ <b>1. Object becomes subject</b>", pasRule1Ex: "Active: She eats an apple → Passive: An apple is eaten",
        pasRule2: "✔️ <b>2. Use V3 (past participle)</b>",
        pasRule3: "✔️ <b>3. Not always needed</b>", pasRule3Desc: "👉 Sometimes passive sounds unnatural in casual speech.",
        pasSumTitle: "🔥 Quick Summary",
        pasSum1: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Passive = be + V3</b> → Focus on action, not the doer",
        pasSum2: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Usage</b> → Often used in formal English",
        // --- CONDITIONALS ---
        condTitle: "Conditionals",
        condIntro: "Conditionals are sentences used to talk about situations and their results.",
        cond0Title: "🔸 0 Conditional (Zero)", cond0Desc: "👉 Used for facts and general truths.",
        cond0Struct: "🧩 <b>If + present simple → present simple</b>",
        cond0Ex1: "If you heat water, it boils.", cond0Ex2: "If I eat too much, I feel sick.",
        cond1Title: "🔸 1st Conditional", cond1Desc: "👉 Used for real and possible future situations.",
        cond1Struct: "🧩 <b>If + present simple → will + verb</b>",
        cond1Ex1: "If it rains, I will stay home.", cond1Ex2: "If you study, you will pass.",
        cond2Title: "🔸 2nd Conditional", cond2Desc: "👉 Used for unreal / imaginary situations (present or future).",
        cond2Struct: "🧩 <b>If + past simple → would + verb</b>",
        cond2Ex1: "If I had money, I would travel.", cond2Ex2: "If I were you, I would study more.",
        cond3Title: "🔸 3rd Conditional", cond3Desc: "👉 Used for past situations that didn’t happen (regret).",
        cond3Struct: "🧩 <b>If + past perfect → would have + V3</b>",
        cond3Ex1: "If I had studied, I would have passed.", cond3Ex2: "If she had left earlier, she would have arrived on time.",
        condMixTitle: "🔥 Mixed Conditionals (optional, B2+)", condMixDesc: "👉 Mix past and present.",
        condMixEx: "If I had studied, I would have a better job now.",
        condRulesTitle: "🔥 Important Rules",
        condRule1: "✔️ <b>1. Comma rule</b>",
        condRule1A: "<b>If</b> it rains<b>,</b> I will stay home.", condRule1B: "I will stay home <b>if</b> it rains. (no comma)",
        condRule2: "✔️ <b>2. “Were” instead of “was”</b>", condRule2Ex: "✅ If I were you (correct)",
        condRule3: "✔️ <b>3. Don’t use “will” after IF</b>",
        condSumTitle: "🔥 Quick Summary",
        condSum0: "<b style='width: 50px; display: inline-block;'>0</b> → facts",
        condSum1: "<b style='width: 50px; display: inline-block;'>1st</b> → real future",
        condSum2: "<b style='width: 50px; display: inline-block;'>2nd</b> → unreal now",
        condSum3: "<b style='width: 50px; display: inline-block;'>3rd</b> → unreal past",
    },
    uk: {
        backHome: "← На головну",
        catNouns: "Іменники та Слова", catVerbs: "Дієслова", catStructure: "Структура",
        topicArticles: "Артиклі (a, an, the)", topicPlurals: "Множина іменників", topicPreps: "Прийменники (in, on, at)", topicModals: "Модальні дієслова", topicPassive: "Пасивний стан", topicCond: "Умовні речення",
        comingSoon: "Контент з'явиться незабаром...",
        artTitle: "Артиклі", artIntro: "Опануйте використання артиклів A, AN та THE в англійській мові.",
        artCard1Title: "🔸 1. A / AN (Неозначені артиклі)",
        artCard1Desc: "👉 Використовується, коли ми говоримо про щось <b>загалом</b> або <b>вперше</b>.",
        artADesc: "Використовується перед словами, що починаються з <b>приголосного</b> звуку.",
        artAnDesc: "Використовується перед словами, що починаються з <b>голосного</b> звуку.",
        exTitle: "📌 <b>Приклади:</b>", exTitle2: "📌 <b>Приклади:</b>", exTitle3: "📌 <b>Приклади:</b>",
        artEx1: "У мене є <b>якийсь</b> собака (a dog).", artEx2: "Вона купила <b>якусь</b> парасольку (an umbrella).",
        artCard2Title: "🔸 2. THE (Означений артикль)",
        artCard2Desc: "👉 Використовується, коли щось є <b>конкретним</b> або вже відоме співрозмовнику.",
        artEx3: "Я бачив собаку. <b>Цей</b> собака був великим.", artEx4: "Зачини <b>ці</b> двері.",
        artWhenThe: "🔸 Коли ще ми використовуємо THE:",
        artUnique: "✔️ Унікальні речі у світі", artGeo: "✔️ Географія (річки, океани)", artSuper: "✔️ Найвищий ступінь",
        artCard3Title: "🔸 3. Без артиклю (Нульовий)",
        artCard3Desc: "👉 Використовується, коли говоримо загалом про множину або незліченні речі.",
        artEx5: "Я люблю музику (загалом).", artEx6: "Собаки дружні (всі собаки).", artEx7: "Вона ходить до школи.",
        artSumTitle: "🔥 Короткий підсумок",
        artSum1: "<b>a / an</b> → щось загальне (один з багатьох)", artSum2: "<b>the</b> → щось конкретне (саме цей)", artSum3: "<b>без артиклю</b> → загальні ідеї / незліченні",
        // --- PLURAL NOUNS ---
        plTitle: "Множина іменників", 
        plIntro: "Множина використовується, коли ми говоримо про більш ніж один предмет.",
        plR1Title: "🔸 1. Правильна множина (додаємо -s)", plR1Desc: "👉 До більшості іменників просто додаємо <b>-s</b>.",
        plR2Title: "🔸 2. Закінчення на -s, -sh, -ch, -x, -z", plR2Desc: "👉 Додаємо <b>-es</b> для полегшення вимови.",
        plR3Title: "🔸 3. Закінчення на -y", 
        plR3C1: "✔️ Приголосна + Y", plR3C1Desc: "Змінюємо -y на <b>-ies</b>.", 
        plR3C2: "✔️ Голосна + Y", plR3C2Desc: "Просто додаємо <b>-s</b>.",
        plR4Title: "🔸 4. Закінчення на -f / -fe", plR4Desc: "👉 Часто змінюється на <b>-ves</b>.", plR4Exc: "⚠️ Винятки:",
        plR5Title: "🔸 5. Неправильна множина (треба запам'ятати)", plR5Desc: "👉 Ці слова не підкоряються правилам.",
        plR6Title: "🔸 6. Однакові в однині та множині",
        exTitle4: "📌 <b>Приклади:</b>", exTitle5: "📌 <b>Приклади:</b>",
        plSumTitle: "🔥 Короткий підсумок",
        plSum1: "<b>додаємо -s</b> → більшість слів", plSum2: "<b>додаємо -es</b> → після s, sh, ch, x, z", 
        plSum3: "<b>-y</b> → -ies (якщо перед нею приголосна)", plSum4: "<b>-f</b> → -ves (часто)", plSum5: "<b>неправильні</b> → вивчити напам'ять",
        // --- PREPOSITIONS ---
        prepTitle: "Прийменники: in, on, at",
        prepIntro: "Ці прийменники використовуються для часу та місця. Вони можуть плутати, але тут є проста логіка 👇",
        prepR1Title: "🔸 1. IN", prepR1Desc: "👉 Використовується для <b>довгих періодів</b> часу та <b>всередині</b> простору.",
        prepTime: "⏰ Час:", prepPlaceIn: "📍 Місце (всередині чогось):",
        prepInEx1: "Я народився <b>в</b> 2008 році.", prepInEx2: "Вона <b>в</b> кімнаті.",
        prepR2Title: "🔸 2. ON", prepR2Desc: "👉 Використовується для <b>днів / дат</b> та <b>поверхонь</b>.",
        prepPlaceOn: "📍 Місце (на поверхні):",
        prepOnEx1: "У мене тест <b>у</b> понеділок.", prepOnEx2: "Телефон <b>на</b> столі.",
        prepR3Title: "🔸 3. AT", prepR3Desc: "👉 Використовується для <b>точного часу</b> та <b>конкретних місць</b>.",
        prepPlaceAt: "📍 Місце (точка/локація):",
        prepAtEx1: "Я прокидаюся <b>о</b> 7 ранку.", prepAtEx2: "Вона <b>на</b> станції.",
        prepCompTitle: "🔥 Швидке порівняння",
        prepTh1: "Прийменник", prepTh2: "Час", prepTh3: "Місце",
        prepTd1: "місяці, роки", prepTd2: "всередині чогось",
        prepTd3: "дні, дати", prepTd4: "на поверхні",
        prepTd5: "точний час", prepTd6: "конкретна точка",
        prepMistakesTitle: "⚠️ Типові помилки:",
        // --- MODAL VERBS ---
        modTitle: "Модальні дієслова",
        modIntro: "Модальні дієслова — це особливі дієслова, що виражають здатність, ймовірність, дозвіл, обов'язок, пораду тощо.",
        modCommonTitle: "🔸 Поширені модальні дієслова",
        modR1Title: "🔸 1. CAN / COULD", modR1Desc: "👉 Здібність / ймовірність / дозвіл",
        modR1Ex1: "I <b>can</b> swim. (здібність)", modR1Ex2: "<b>Can</b> I go out? (дозвіл)", modR1Ex3: "It <b>could</b> rain. (ймовірність)",
        modR2Title: "🔸 2. MAY / MIGHT", modR2Desc: "👉 Ймовірність (більш формально / менш впевнено)",
        modR2Ex1: "It <b>may</b> rain. (Можливо піде дощ)", modR2Ex2: "She <b>might</b> come later. (Вона, можливо, прийде)",
        modR3Title: "🔸 3. MUST / HAVE TO", modR3Desc: "👉 Обов'язок / необхідність",
        modR3Ex1: "You <b>must</b> study. (особисте переконання / суворий наказ)", modR3Ex2: "I <b>have to</b> wake up early. (зовнішня обставина / правило)",
        modR4Title: "🔸 4. SHOULD", modR4Desc: "👉 Порада / рекомендація",
        modR4Ex1: "You <b>should</b> sleep more. (Тобі слід більше спати)", modR4Ex2: "He <b>should</b> apologize. (Йому варто вибачитися)",
        modR5Title: "🔸 5. WILL / WOULD", modR5Desc: "👉 Майбутній час / ввічливі прохання / умови",
        modR5Ex1: "I <b>will</b> call you. (Я зателефоную тобі)", modR5Ex2: "<b>Would</b> you help me? (Чи не міг би ти допомогти?)", modR5Ex3: "I <b>would</b> go if I had time. (Я б пішов, якби мав час)",
        modRulesTitle: "🔥 Важливі правила",
        modRule1: "✔️ <b>1. Жодних “to” після модальних дієслів</b>",
        modRule2: "✔️ <b>2. Дієслово завжди в початковій формі</b>",
        modRule3: "✔️ <b>3. Ніяких -s у третій особі (he, she, it)</b>",
        modSumTitle: "🔥 Короткий підсумок",
        modSum1: "<b style='width: 150px;'>can</b> → здатність / вміння",
        modSum2: "<b style='width: 150px;'>could / might / may</b> → ймовірність",
        modSum3: "<b style='width: 150px;'>must / have to</b> → обов'язок",
        modSum4: "<b style='width: 150px;'>should</b> → порада",
        modSum5: "<b style='width: 150px;'>will / would</b> → майбутнє / ввічливість",
        // --- PASSIVE VOICE ---
        pasTitle: "Пасивний стан (Passive Voice)",
        pasIntro: "Пасивний стан використовується, коли дія важливіша за того, хто її виконує, або коли виконавець невідомий.",
        pasR1Title: "🔸 Структура", pasR1Desc: "👉 <b>be</b> (у потрібному часі) + <b>past participle (V3)</b>",
        pasR1Ex1: "Актив: She writes a letter (Вона пише лист)", pasR1Ex2: "Пасив: A letter <b>is written</b> (Лист пишеться)",
        pasR2Title: "🔸 Коли використовувати",
        pasUse1: "✔️ 1. Виконавець невідомий", pasUse1Ex: "My phone <b>was stolen</b> (Мій телефон вкрали)",
        pasUse2: "✔️ 2. Виконавець неважливий", pasUse2Ex: "The road <b>is being repaired</b> (Дорогу ремонтують)",
        pasUse3: "✔️ 3. Формальний / науковий стиль", pasUse3Ex: "The experiment <b>was conducted</b> (Експеримент було проведено)",
        pasR3Title: "🔸 Пасив у різних часах",
        pasT1A: "Актив: They make cars", pasT1P: "Пасив: Cars <b>are made</b>",
        pasT2A: "Актив: They built a house", pasT2P: "Пасив: A house <b>was built</b>",
        pasT3A: "Актив: They will finish the work", pasT3P: "Пасив: The work <b>will be finished</b>",
        pasT4A: "Актив: They are building a bridge", pasT4P: "Пасив: A bridge <b>is being built</b>",
        pasT5A: "Актив: They have cleaned the room", pasT5P: "Пасив: The room <b>has been cleaned</b>",
        pasR4Title: "🔸 By + Виконавець", pasR4Desc: "👉 Використовуй <b>by</b>, якщо хочеш вказати, хто виконав дію.",
        pasR4Ex1: "The book was written <b>by him</b> (написана ним)", pasR4Ex2: "The song was sung <b>by her</b> (заспівана нею)",
        pasRulesTitle: "🔥 Важливі правила",
        pasRule1: "✔️ <b>1. Додаток стає підметом</b>", pasRule1Ex: "Актив: Вона їсть яблуко → Пасив: Яблуко з'їдене",
        pasRule2: "✔️ <b>2. Використовуй V3 (третю форму)</b>",
        pasRule3: "✔️ <b>3. Не завжди потрібен</b>", pasRule3Desc: "👉 Іноді пасив звучить неприродно в повсякденній розмові.",
        pasSumTitle: "🔥 Короткий підсумок",
        pasSum1: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Пасив = be + V3</b> → Фокус на дії, а не на виконавці",
        pasSum2: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Використання</b> → Часто вживається у формальній англійській",
        // --- CONDITIONALS ---
        condTitle: "Умовні речення (Conditionals)",
        condIntro: "Умовні речення використовуються, щоб говорити про ситуації та їхні наслідки.",
        cond0Title: "🔸 0 Conditional (Нульовий)", cond0Desc: "👉 Факти та загальні істини.",
        cond0Struct: "🧩 <b>If + present simple → present simple</b>",
        cond0Ex1: "If you heat water, it boils. (Якщо нагріти воду, вона закипить)", cond0Ex2: "If I eat too much, I feel sick. (Якщо я переїдаю, мені погано)",
        cond1Title: "🔸 1st Conditional (Перший)", cond1Desc: "👉 Реальні та можливі ситуації в майбутньому.",
        cond1Struct: "🧩 <b>If + present simple → will + verb</b>",
        cond1Ex1: "If it rains, I will stay home. (Якщо піде дощ, я залишуся вдома)", cond1Ex2: "If you study, you will pass. (Якщо будеш вчитися, ти здаш)",
        cond2Title: "🔸 2nd Conditional (Другий)", cond2Desc: "👉 Нереальні / уявні ситуації (теперішнє або майбутнє).",
        cond2Struct: "🧩 <b>If + past simple → would + verb</b>",
        cond2Ex1: "If I had money, I would travel. (Якби я мав гроші, я б подорожував)", cond2Ex2: "If I were you, I would study more. (На твоєму місці я б вчився більше)",
        cond3Title: "🔸 3rd Conditional (Третій)", cond3Desc: "👉 Минулі ситуації, які не відбулися (жаль про минуле).",
        cond3Struct: "🧩 <b>If + past perfect → would have + V3</b>",
        cond3Ex1: "If I had studied, I would have passed. (Якби я вчився тоді, я б здав)", cond3Ex2: "If she had left earlier, she would have arrived on time. (Якби вона вийшла раніше, вона б прибула вчасно)",
        condMixTitle: "🔥 Змішані типи (B2+)", condMixDesc: "👉 Мікс минулого та теперішнього.",
        condMixEx: "If I had studied, I would have a better job now. (Якби я вчився в минулому, я б мав кращу роботу зараз)",
        condRulesTitle: "🔥 Важливі правила",
        condRule1: "✔️ <b>1. Правило коми</b>",
        condRule1A: "<b>If</b> it rains<b>,</b> I will stay home. (Кома потрібна)", condRule1B: "I will stay home <b>if</b> it rains. (Без коми)",
        condRule2: "✔️ <b>2. “Were” замість “was”</b>", condRule2Ex: "✅ If I were you (правильно)",
        condRule3: "✔️ <b>3. Не використовуй “will” після IF</b>",
        condSumTitle: "🔥 Короткий підсумок",
        condSum0: "<b style='width: 50px; display: inline-block;'>0</b> → факти",
        condSum1: "<b style='width: 50px; display: inline-block;'>1st</b> → реальне майбутнє",
        condSum2: "<b style='width: 50px; display: inline-block;'>2nd</b> → нереальне зараз",
        condSum3: "<b style='width: 50px; display: inline-block;'>3rd</b> → нереальне минуле",
},
    pl: {
        backHome: "← Strona główna",
        catNouns: "Rzeczowniki i Słowa", catVerbs: "Czasowniki", catStructure: "Struktura",
        topicArticles: "Przedimki (a, an, the)", topicPlurals: "Liczba mnoga", topicPreps: "Przyimki (in, on, at)", topicModals: "Czasowniki modalne", topicPassive: "Strona bierna", topicCond: "Okresy warunkowe",
        comingSoon: "Wkrótce...",
        artTitle: "Przedimki", artIntro: "Opanuj użycie przedimków A, AN i THE w języku angielskim.",
        artCard1Title: "🔸 1. A / AN (Przedimek nieokreślony)",
        artCard1Desc: "👉 Używany, gdy mówimy o czymś <b>ogólnie</b> lub po raz <b>pierwszy</b>.",
        artADesc: "Przed słowami zaczynającymi się od <b>spółgłoski</b>.",
        artAnDesc: "Przed słowami zaczynającymi się od <b>samogłoski</b>.",
        exTitle: "📌 <b>Przykłady:</b>", exTitle2: "📌 <b>Przykłady:</b>", exTitle3: "📌 <b>Przykłady:</b>",
        artEx1: "Mam psa (a dog).", artEx2: "Kupiła parasol (an umbrella).",
        artCard2Title: "🔸 2. THE (Przedimek określony)",
        artCard2Desc: "👉 Używany, gdy coś jest <b>konkretne</b> lub już znane słuchaczowi.",
        artEx3: "Widziałem psa. <b>Ten</b> pies był duży.", artEx4: "Zamknij <b>te</b> drzwi.",
        artWhenThe: "🔸 Kiedy jeszcze używamy THE:",
        artUnique: "✔️ Unikalne rzeczy", artGeo: "✔️ Geografia", artSuper: "✔️ Stopień najwyższy",
        artCard3Title: "🔸 3. Brak przedimka (Zero Article)",
        artCard3Desc: "👉 Używany, gdy mówimy ogólnie o rzeczownikach w liczbie mnogiej lub niepoliczalnych.",
        artEx5: "Lubię muzykę.", artEx6: "Psy są przyjazne.", artEx7: "Ona chodzi do szkoły.",
        artSumTitle: "🔥 Podsumowanie",
        artSum1: "<b>a / an</b> → coś ogólnego", artSum2: "<b>the</b> → coś konkretnego", artSum3: "<b>brak</b> → ogólne idee / niepoliczalne",
        // --- PLURAL NOUNS ---
        plTitle: "Liczba mnoga", 
        plIntro: "Liczby mnogiej używamy, gdy mówimy o więcej niż jednej rzeczy.",
        plR1Title: "🔸 1. Regularna liczba mnoga (dodaj -s)", plR1Desc: "👉 Do większości rzeczowników po prostu dodajemy <b>-s</b>.",
        plR2Title: "🔸 2. Rzeczowniki zakończone na -s, -sh, -ch, -x, -z", plR2Desc: "👉 Dodajemy <b>-es</b>, aby ułatwić wymowę.",
        plR3Title: "🔸 3. Rzeczowniki zakończone na -y", 
        plR3C1: "✔️ Spółgłoska + Y", plR3C1Desc: "Zamieniamy -y na <b>-ies</b>.", 
        plR3C2: "✔️ Samogłoska + Y", plR3C2Desc: "Po prostu dodajemy <b>-s</b>.",
        plR4Title: "🔸 4. Rzeczowniki zakończone na -f / -fe", plR4Desc: "👉 Często zmieniają się na <b>-ves</b>.", plR4Exc: "⚠️ Wyjątki:",
        plR5Title: "🔸 5. Nieregularna liczba mnoga (trzeba zapamiętać)", plR5Desc: "👉 Te słowa nie podlegają regułom.",
        plR6Title: "🔸 6. Takie same w liczbie pojedynczej i mnogiej",
        exTitle4: "📌 <b>Przykłady:</b>", exTitle5: "📌 <b>Przykłady:</b>",
        plSumTitle: "🔥 Podsumowanie",
        plSum1: "<b>dodaj -s</b> → większość słów", plSum2: "<b>dodaj -es</b> → po s, sh, ch, x, z", 
        plSum3: "<b>-y</b> → -ies (jeśli wcześniej jest spółgłoska)", plSum4: "<b>-f</b> → -ves (często)", plSum5: "<b>nieregularne</b> → naucz się na pamięć",
        // --- PREPOSITIONS ---
        prepTitle: "Przyimki: in, on, at",
        prepIntro: "Te przyimki są używane do określania czasu i miejsca. Mogą być mylące, ale jest w tym prosta logika 👇",
        prepR1Title: "🔸 1. IN", prepR1Desc: "👉 Używane do <b>dłuższych okresów</b> czasu i <b>wewnątrz</b> pomieszczeń.",
        prepTime: "⏰ Czas:", prepPlaceIn: "📍 Miejsce (wewnątrz czegoś):",
        prepInEx1: "Urodziłem się <b>w</b> 2008 roku.", prepInEx2: "Ona jest <b>w</b> pokoju.",
        prepR2Title: "🔸 2. ON", prepR2Desc: "👉 Używane do <b>dni / dat</b> i <b>powierzchni</b>.",
        prepPlaceOn: "📍 Miejsce (na powierzchni):",
        prepOnEx1: "Mam test <b>w</b> poniedziałek.", prepOnEx2: "Telefon leży <b>na</b> stole.",
        prepR3Title: "🔸 3. AT", prepR3Desc: "👉 Używane do <b>dokładnego czasu</b> i <b>konkretnych miejsc</b>.",
        prepPlaceAt: "📍 Miejsce (punkt/lokalizacja):",
        prepAtEx1: "Budzę się <b>o</b> 7 rano.", prepAtEx2: "Ona jest <b>na</b> stacji.",
        prepCompTitle: "🔥 Szybkie porównanie",
        prepTh1: "Przyimek", prepTh2: "Czas", prepTh3: "Miejsce",
        prepTd1: "miesiące, lata", prepTd2: "wewnątrz czegoś",
        prepTd3: "dni, daty", prepTd4: "na powierzchni",
        prepTd5: "dokładny czas", prepTd6: "konkretny punkt",
        prepMistakesTitle: "⚠️ Częste błędy:",
        // --- MODAL VERBS ---
        modTitle: "Czasowniki modalne",
        modIntro: "Czasowniki modalne to specjalne czasowniki używane do wyrażania zdolności, możliwości, pozwolenia, obowiązku, rady itp.",
        modCommonTitle: "🔸 Popularne czasowniki modalne",
        modR1Title: "🔸 1. CAN / COULD", modR1Desc: "👉 Zdolność / możliwość / pozwolenie",
        modR1Ex1: "I <b>can</b> swim. (zdolność)", modR1Ex2: "<b>Can</b> I go out? (pozwolenie)", modR1Ex3: "It <b>could</b> rain. (możliwość)",
        modR2Title: "🔸 2. MAY / MIGHT", modR2Desc: "👉 Możliwość (bardziej formalne / mniejsza pewność)",
        modR2Ex1: "It <b>may</b> rain. (Może padać)", modR2Ex2: "She <b>might</b> come later. (Ona może przyjść później)",
        modR3Title: "🔸 3. MUST / HAVE TO", modR3Desc: "👉 Obowiązek / konieczność",
        modR3Ex1: "You <b>must</b> study. (silny obowiązek / nakaz)", modR3Ex2: "I <b>have to</b> wake up early. (zasada / sytuacja)",
        modR4Title: "🔸 4. SHOULD", modR4Desc: "👉 Rada / rekomendacja",
        modR4Ex1: "You <b>should</b> sleep more. (Powinieneś spać więcej)", modR4Ex2: "He <b>should</b> apologize. (On powinien przeprosić)",
        modR5Title: "🔸 5. WILL / WOULD", modR5Desc: "👉 Przyszłość / uprzejme prośby / okresy warunkowe",
        modR5Ex1: "I <b>will</b> call you. (Zadzwonię do ciebie)", modR5Ex2: "<b>Would</b> you help me? (Czy mógłbyś mi pomóc?)", modR5Ex3: "I <b>would</b> go if I had time. (Poszedłbym, gdybym miał czas)",
        modRulesTitle: "🔥 Ważne zasady",
        modRule1: "✔️ <b>1. Brak “to” po czasownikach modalnych</b>",
        modRule2: "✔️ <b>2. Czasownik w formie podstawowej</b>",
        modRule3: "✔️ <b>3. Brak -s w 3. osobie (he, she, it)</b>",
        modSumTitle: "🔥 Podsumowanie",
        modSum1: "<b style='width: 150px;'>can</b> → zdolność",
        modSum2: "<b style='width: 150px;'>could / might / may</b> → możliwość",
        modSum3: "<b style='width: 150px;'>must / have to</b> → obowiązek",
        modSum4: "<b style='width: 150px;'>should</b> → rada",
        modSum5: "<b style='width: 150px;'>will / would</b> → przyszłość / uprzejmość",
        // --- PASSIVE VOICE ---
        pasTitle: "Strona bierna (Passive Voice)",
        pasIntro: "Strona bierna jest używana, gdy czynność jest ważniejsza niż osoba, która ją wykonuje, lub gdy wykonawca jest nieznany.",
        pasR1Title: "🔸 Struktura", pasR1Desc: "👉 <b>be</b> (w odpowiednim czasie) + <b>past participle (V3)</b>",
        pasR1Ex1: "Czynna: She writes a letter", pasR1Ex2: "Bierna: A letter <b>is written</b> (by her)",
        pasR2Title: "🔸 Kiedy używać strony biernej",
        pasUse1: "✔️ 1. Wykonawca jest nieznany", pasUse1Ex: "My phone <b>was stolen</b> (Skradziono mi telefon)",
        pasUse2: "✔️ 2. Wykonawca jest nieważny", pasUse2Ex: "The road <b>is being repaired</b> (Droga jest naprawiana)",
        pasUse3: "✔️ 3. Styl formalny / naukowy", pasUse3Ex: "The experiment <b>was conducted</b> (Eksperyment został przeprowadzony)",
        pasR3Title: "🔸 Strona bierna w różnych czasach",
        pasT1A: "Czynna: They make cars", pasT1P: "Bierna: Cars <b>are made</b>",
        pasT2A: "Czynna: They built a house", pasT2P: "Bierna: A house <b>was built</b>",
        pasT3A: "Czynna: They will finish the work", pasT3P: "Bierna: The work <b>will be finished</b>",
        pasT4A: "Czynna: They are building a bridge", pasT4P: "Bierna: A bridge <b>is being built</b>",
        pasT5A: "Czynna: They have cleaned the room", pasT5P: "Bierna: The room <b>has been cleaned</b>",
        pasR4Title: "🔸 By + Wykonawca", pasR4Desc: "👉 Użyj <b>by</b>, jeśli chcesz powiedzieć, kto wykonał czynność.",
        pasR4Ex1: "The book was written <b>by him</b> (przez niego)", pasR4Ex2: "The song was sung <b>by her</b> (przez nią)",
        pasRulesTitle: "🔥 Ważne zasady",
        pasRule1: "✔️ <b>1. Dopełnienie staje się podmiotem</b>", pasRule1Ex: "Czynna: Ona je jabłko → Bierna: Jabłko jest jedzone",
        pasRule2: "✔️ <b>2. Używaj V3 (past participle)</b>",
        pasRule3: "✔️ <b>3. Nie zawsze potrzebna</b>", pasRule3Desc: "👉 Czasami strona bierna brzmi nienaturalnie w mowie potocznej.",
        pasSumTitle: "🔥 Podsumowanie",
        pasSum1: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Bierna = be + V3</b> → Skupienie na czynności, nie na wykonawcy",
        pasSum2: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Użycie</b> → Często używana w formalnym angielskim",
        // --- CONDITIONALS ---
        condTitle: "Okresy warunkowe (Conditionals)",
        condIntro: "Okresy warunkowe służą do mówienia o sytuacjach i ich skutkach.",
        cond0Title: "🔸 0 Conditional (Zerowy)", cond0Desc: "👉 Fakty i prawdy ogólne.",
        cond0Struct: "🧩 <b>If + present simple → present simple</b>",
        cond0Ex1: "If you heat water, it boils. (Jeśli podgrzejesz wodę, zagotuje się)", cond0Ex2: "If I eat too much, I feel sick. (Jeśli zjem za dużo, jest mi niedobrze)",
        cond1Title: "🔸 1st Conditional (Pierwszy)", cond1Desc: "👉 Realne i możliwe sytuacje w przyszłości.",
        cond1Struct: "🧩 <b>If + present simple → will + verb</b>",
        cond1Ex1: "If it rains, I will stay home. (Jeśli będzie padać, zostanę w domu)", cond1Ex2: "If you study, you will pass. (Jeśli będziesz się uczyć, zdasz)",
        cond2Title: "🔸 2nd Conditional (Drugi)", cond2Desc: "👉 Nierzeczywiste / wyobrażone sytuacje (teraz lub w przyszłości).",
        cond2Struct: "🧩 <b>If + past simple → would + verb</b>",
        cond2Ex1: "If I had money, I would travel. (Gdybym miał pieniądze, podróżowałbym)", cond2Ex2: "If I were you, I would study more. (Na twoim miejscu uczyłbym się więcej)",
        cond3Title: "🔸 3rd Conditional (Trzeci)", cond3Desc: "👉 Sytuacje w przeszłości, które się nie wydarzyły (żal).",
        cond3Struct: "🧩 <b>If + past perfect → would have + V3</b>",
        cond3Ex1: "If I had studied, I would have passed. (Gdybym się uczył, zdałbym)", cond3Ex2: "If she had left earlier, she would have arrived on time. (Gdyby wyszła wcześniej, dotarłaby na czas)",
        condMixTitle: "🔥 Mixed Conditionals (Mieszane)", condMixDesc: "👉 Łączenie przeszłości z teraźniejszością.",
        condMixEx: "If I had studied, I would have a better job now. (Gdybym się uczył w przeszłości, miałbym teraz lepszą pracę)",
        condRulesTitle: "🔥 Ważne zasady",
        condRule1: "✔️ <b>1. Zasada przecinka</b>",
        condRule1A: "<b>If</b> it rains<b>,</b> I will stay home. (Z przecinkiem)", condRule1B: "I will stay home <b>if</b> it rains. (Bez przecinka)",
        condRule2: "✔️ <b>2. “Were” zamiast “was”</b>", condRule2Ex: "✅ If I were you (poprawnie)",
        condRule3: "✔️ <b>3. Nie używaj “will” po IF</b>",
        condSumTitle: "🔥 Podsumowanie",
        condSum0: "<b style='width: 50px; display: inline-block;'>0</b> → fakty",
        condSum1: "<b style='width: 50px; display: inline-block;'>1st</b> → realna przyszłość",
        condSum2: "<b style='width: 50px; display: inline-block;'>2nd</b> → nierealne teraz",
        condSum3: "<b style='width: 50px; display: inline-block;'>3rd</b> → nierealna przeszłość",
},
    ru: {
        backHome: "← На главную",
        catNouns: "Существительные и Слова", catVerbs: "Глаголы", catStructure: "Структура",
        topicArticles: "Артикли (a, an, the)", topicPlurals: "Множественное число", topicPreps: "Предлоги (in, on, at)", topicModals: "Модальные глаголы", topicPassive: "Пассивный залог", topicCond: "Условные предложения",
        comingSoon: "Контент появится скоро...",
        artTitle: "Артикли", artIntro: "Освойте использование артиклей A, AN и THE в английском языке.",
        artCard1Title: "🔸 1. A / AN (Неопределенные артикли)",
        artCard1Desc: "👉 Используется, когда мы говорим о чем-то <b>в целом</b> или <b>впервые</b>.",
        artADesc: "Перед словами, начинающимися с <b>согласного</b> звука.",
        artAnDesc: "Перед словами, начинающимися с <b>гласного</b> звука.",
        exTitle: "📌 <b>Примеры:</b>", exTitle2: "📌 <b>Примеры:</b>", exTitle3: "📌 <b>Примеры:</b>",
        artEx1: "У меня есть собака (a dog).", artEx2: "Она купила зонтик (an umbrella).",
        artCard2Title: "🔸 2. THE (Определенный артикль)",
        artCard2Desc: "👉 Используется, когда что-то <b>конкретное</b> или уже известно собеседнику.",
        artEx3: "Я видел собаку. <b>Эта</b> собака была большой.", artEx4: "Закрой дверь.",
        artWhenThe: "🔸 Когда еще мы используем THE:",
        artUnique: "✔️ Уникальные вещи", artGeo: "✔️ География", artSuper: "✔️ Превосходная степень",
        artCard3Title: "🔸 3. Без артикля (Нулевой артикль)",
        artCard3Desc: "👉 Используется, когда говорим в целом о множественном числе или неисчисляемых вещах.",
        artEx5: "Я люблю музыку.", artEx6: "Собаки дружелюбны.", artEx7: "Она ходит в школу.",
        artSumTitle: "🔥 Краткий итог",
        artSum1: "<b>a / an</b> → что-то общее", artSum2: "<b>the</b> → что-то конкретное", artSum3: "<b>без артикля</b> → общие идеи / неисчисляемые",
        // --- PLURAL NOUNS ---
        plTitle: "Множественное число", 
        plIntro: "Множественное число используется, когда мы говорим о более чем одном предмете.",
        plR1Title: "🔸 1. Правильное множественное число (добавляем -s)", plR1Desc: "👉 К большинству существительных просто добавляем <b>-s</b>.",
        plR2Title: "🔸 2. Окончания на -s, -sh, -ch, -x, -z", plR2Desc: "👉 Добавляем <b>-es</b> для облегчения произношения.",
        plR3Title: "🔸 3. Окончания на -y", 
        plR3C1: "✔️ Согласная + Y", plR3C1Desc: "Меняем -y на <b>-ies</b>.", 
        plR3C2: "✔️ Гласная + Y", plR3C2Desc: "Просто добавляем <b>-s</b>.",
        plR4Title: "🔸 4. Окончания на -f / -fe", plR4Desc: "👉 Часто меняется на <b>-ves</b>.", plR4Exc: "⚠️ Исключения:",
        plR5Title: "🔸 5. Неправильное множественное число (надо запомнить)", plR5Desc: "👉 Эти слова не подчиняются правилам.",
        plR6Title: "🔸 6. Одинаковые в ед. и мн. числе",
        exTitle4: "📌 <b>Примеры:</b>", exTitle5: "📌 <b>Примеры:</b>",
        plSumTitle: "🔥 Краткий итог",
        plSum1: "<b>добавляем -s</b> → большинство слов", plSum2: "<b>добавляем -es</b> → после s, sh, ch, x, z", 
        plSum3: "<b>-y</b> → -ies (если перед ней согласная)", plSum4: "<b>-f</b> → -ves (часто)", plSum5: "<b>неправильные</b> → выучить наизусть",
        // --- PREPOSITIONS ---
        prepTitle: "Предлоги: in, on, at",
        prepIntro: "Эти предлоги используются для времени и места. Они могут путать, но здесь есть простая логика 👇",
        prepR1Title: "🔸 1. IN", prepR1Desc: "👉 Используется для <b>длинных периодов</b> времени и <b>внутри</b> пространств.",
        prepTime: "⏰ Время:", prepPlaceIn: "📍 Место (внутри чего-то):",
        prepInEx1: "Я родился <b>в</b> 2008 году.", prepInEx2: "Она <b>в</b> комнате.",
        prepR2Title: "🔸 2. ON", prepR2Desc: "👉 Используется для <b>дней / дат</b> и <b>поверхностей</b>.",
        prepPlaceOn: "📍 Место (на поверхности):",
        prepOnEx1: "У меня тест <b>в</b> понедельник.", prepOnEx2: "Телефон <b>на</b> столе.",
        prepR3Title: "🔸 3. AT", prepR3Desc: "👉 Используется для <b>точного времени</b> и <b>конкретных мест</b>.",
        prepPlaceAt: "📍 Место (точка/локация):",
        prepAtEx1: "Я просыпаюсь <b>в</b> 7 утра.", prepAtEx2: "Она <b>на</b> станции.",
        prepCompTitle: "🔥 Быстрое сравнение",
        prepTh1: "Предлог", prepTh2: "Время", prepTh3: "Место",
        prepTd1: "месяцы, годы", prepTd2: "внутри чего-то",
        prepTd3: "дни, даты", prepTd4: "на поверхности",
        prepTd5: "точное время", prepTd6: "конкретная точка",
        prepMistakesTitle: "⚠️ Частые ошибки:",
        // --- MODAL VERBS ---
        modTitle: "Модальные глаголы",
        modIntro: "Модальные глаголы — это особые глаголы, выражающие способность, вероятность, разрешение, обязанность, совет и т.д.",
        modCommonTitle: "🔸 Популярные модальные глаголы",
        modR1Title: "🔸 1. CAN / COULD", modR1Desc: "👉 Способность / вероятность / разрешение",
        modR1Ex1: "I <b>can</b> swim. (способность)", modR1Ex2: "<b>Can</b> I go out? (разрешение)", modR1Ex3: "It <b>could</b> rain. (вероятность)",
        modR2Title: "🔸 2. MAY / MIGHT", modR2Desc: "👉 Вероятность (более формально / меньше уверенности)",
        modR2Ex1: "It <b>may</b> rain. (Возможно пойдет дождь)", modR2Ex2: "She <b>might</b> come later. (Она, возможно, придет)",
        modR3Title: "🔸 3. MUST / HAVE TO", modR3Desc: "👉 Обязанность / необходимость",
        modR3Ex1: "You <b>must</b> study. (личное убеждение / строгий приказ)", modR3Ex2: "I <b>have to</b> wake up early. (внешнее обстоятельство / правило)",
        modR4Title: "🔸 4. SHOULD", modR4Desc: "👉 Совет / рекомендация",
        modR4Ex1: "You <b>should</b> sleep more. (Тебе следует больше спать)", modR4Ex2: "He <b>should</b> apologize. (Ему следует извиниться)",
        modR5Title: "🔸 5. WILL / WOULD", modR5Desc: "👉 Будущее / вежливые просьбы / условия",
        modR5Ex1: "I <b>will</b> call you. (Я позвоню тебе)", modR5Ex2: "<b>Would</b> you help me? (Не мог бы ты помочь?)", modR5Ex3: "I <b>would</b> go if I had time. (Я бы пошел, если бы было время)",
        modRulesTitle: "🔥 Важные правила",
        modRule1: "✔️ <b>1. Никаких “to” после модальных глаголов</b>",
        modRule2: "✔️ <b>2. Глагол всегда в начальной форме</b>",
        modRule3: "✔️ <b>3. Никаких -s в третьем лице (he, she, it)</b>",
        modSumTitle: "🔥 Краткий итог",
        modSum1: "<b style='width: 150px;'>can</b> → способность / умение",
        modSum2: "<b style='width: 150px;'>could / might / may</b> → вероятность",
        modSum3: "<b style='width: 150px;'>must / have to</b> → обязанность",
        modSum4: "<b style='width: 150px;'>should</b> → совет",
        modSum5: "<b style='width: 150px;'>will / would</b> → будущее / вежливость",
        // --- PASSIVE VOICE ---
        pasTitle: "Пассивный залог (Passive Voice)",
        pasIntro: "Пассивный залог используется, когда действие важнее того, кто его выполняет, или когда исполнитель неизвестен.",
        pasR1Title: "🔸 Структура", pasR1Desc: "👉 <b>be</b> (в нужном времени) + <b>past participle (V3)</b>",
        pasR1Ex1: "Актив: She writes a letter", pasR1Ex2: "Пассив: A letter <b>is written</b> (Письмо пишется)",
        pasR2Title: "🔸 Когда использовать",
        pasUse1: "✔️ 1. Исполнитель неизвестен", pasUse1Ex: "My phone <b>was stolen</b> (Мой телефон украли)",
        pasUse2: "✔️ 2. Исполнитель неважен", pasUse2Ex: "The road <b>is being repaired</b> (Дорогу ремонтируют)",
        pasUse3: "✔️ 3. Формальный / научный стиль", pasUse3Ex: "The experiment <b>was conducted</b> (Эксперимент был проведен)",
        pasR3Title: "🔸 Пассив в разных временах",
        pasT1A: "Актив: They make cars", pasT1P: "Пассив: Cars <b>are made</b>",
        pasT2A: "Актив: They built a house", pasT2P: "Пассив: A house <b>was built</b>",
        pasT3A: "Актив: They will finish the work", pasT3P: "Пассив: The work <b>will be finished</b>",
        pasT4A: "Актив: They are building a bridge", pasT4P: "Пассив: A bridge <b>is being built</b>",
        pasT5A: "Актив: They have cleaned the room", pasT5P: "Пассив: The room <b>has been cleaned</b>",
        pasR4Title: "🔸 By + Исполнитель", pasR4Desc: "👉 Используй <b>by</b>, если хочешь указать, кто выполнил действие.",
        pasR4Ex1: "The book was written <b>by him</b> (им)", pasR4Ex2: "The song was sung <b>by her</b> (ею)",
        pasRulesTitle: "🔥 Важные правила",
        pasRule1: "✔️ <b>1. Дополнение становится подлежащим</b>", pasRule1Ex: "Актив: Она ест яблоко → Пассив: Яблоко съедено",
        pasRule2: "✔️ <b>2. Используй V3 (третью форму)</b>",
        pasRule3: "✔️ <b>3. Не всегда нужен</b>", pasRule3Desc: "👉 Иногда пассив звучит неестественно в разговорной речи.",
        pasSumTitle: "🔥 Краткий итог",
        pasSum1: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Пассив = be + V3</b> → Фокус на действии, а не на исполнителе",
        pasSum2: "<b style='width: 190px; white-space: nowrap; display: inline-block;'>Использование</b> → Часто в формальном английском",
    // --- CONDITIONALS ---
        condTitle: "Условные предложения (Conditionals)",
        condIntro: "Условные предложения используются, чтобы говорить о ситуациях и их последствиях.",
        cond0Title: "🔸 0 Conditional (Нулевой)", cond0Desc: "👉 Факты и общие истины.",
        cond0Struct: "🧩 <b>If + present simple → present simple</b>",
        cond0Ex1: "If you heat water, it boils. (Если нагреть воду, она закипит)", cond0Ex2: "If I eat too much, I feel sick. (Если я переедаю, мне плохо)",
        cond1Title: "🔸 1st Conditional (Первый)", cond1Desc: "👉 Реальные и возможные ситуации в будущем.",
        cond1Struct: "🧩 <b>If + present simple → will + verb</b>",
        cond1Ex1: "If it rains, I will stay home. (Если пойдет дождь, я останусь дома)", cond1Ex2: "If you study, you will pass. (Если будешь учиться, ты сдашь)",
        cond2Title: "🔸 2nd Conditional (Второй)", cond2Desc: "👉 Нереальные / воображаемые ситуации (настоящее или будущее).",
        cond2Struct: "🧩 <b>If + past simple → would + verb</b>",
        cond2Ex1: "If I had money, I would travel. (Если бы у меня были деньги, я бы путешествовал)", cond2Ex2: "If I were you, I would study more. (На твоем месте я бы учился больше)",
        cond3Title: "🔸 3rd Conditional (Третий)", cond3Desc: "👉 Прошлые ситуации, которые не произошли (сожаление).",
        cond3Struct: "🧩 <b>If + past perfect → would have + V3</b>",
        cond3Ex1: "If I had studied, I would have passed. (Если бы я учился тогда, я бы сдал)", cond3Ex2: "If she had left earlier, she would have arrived on time. (Если бы она вышла раньше, она бы прибыла вовремя)",
        condMixTitle: "🔥 Смешанные типы (B2+)", condMixDesc: "👉 Микс прошлого и настоящего.",
        condMixEx: "If I had studied, I would have a better job now. (Если бы я учился в прошлом, у меня была бы лучшая работа сейчас)",
        condRulesTitle: "🔥 Важные правила",
        condRule1: "✔️ <b>1. Правило запятой</b>",
        condRule1A: "<b>If</b> it rains<b>,</b> I will stay home. (Запятая нужна)", condRule1B: "I will stay home <b>if</b> it rains. (Без запятой)",
        condRule2: "✔️ <b>2. “Were” вместо “was”</b>", condRule2Ex: "✅ If I were you (правильно)",
        condRule3: "✔️ <b>3. Не используй “will” после IF</b>",
        condSumTitle: "🔥 Краткий итог",
        condSum0: "<b style='width: 50px; display: inline-block;'>0</b> → факты",
        condSum1: "<b style='width: 50px; display: inline-block;'>1st</b> → реальное будущее",
        condSum2: "<b style='width: 50px; display: inline-block;'>2nd</b> → нереальное сейчас",
        condSum3: "<b style='width: 50px; display: inline-block;'>3rd</b> → нереальное прошлое",
    }
};

// Логіка перемикання тем
function showTopic(topicId, btnElement) {
    document.querySelectorAll('.topic-btn').forEach(btn => btn.classList.remove('active'));
    btnElement.classList.add('active');
    document.querySelectorAll('.topic-content').forEach(content => content.classList.remove('active'));
    document.getElementById(topicId).classList.add('active');
    if(window.innerWidth < 900) { document.querySelector('.content-area').scrollIntoView({ behavior: 'smooth' }); }
}

// function changeLanguage(langCode, langName) {
//     // 1. Оновлюємо кнопку в шапці
//     document.getElementById('currentLang').innerHTML = langName + ' ▾';
    
//     // 2. Зберігаємо мову в кеш, щоб вона не злітала при переході на інші сторінки
//     localStorage.setItem('selectedLang', langCode);

//     const elements = document.querySelectorAll(".translatable");

//     elements.forEach(element => {
//         // Ховаємо текст (анімація згасання)
//         element.style.opacity = 0; 
        
//         setTimeout(() => {
//             const key = element.getAttribute("data-key");
//             if (translations[langCode] && translations[langCode][key] !== undefined) {
//                 // ВАЖЛИВО: використовуємо innerHTML, щоб теги <b> працювали!
//                 element.innerHTML = translations[langCode][key]; 
//             }
//             // Показуємо новий перекладений текст
//             element.style.opacity = 1; 
//         }, 300); // 300 мілісекунд затримки, як у твоєму коді
//     });
// }

window.addEventListener('DOMContentLoaded', () => {
    if (typeof window.applySavedLanguage === 'function') {
        window.applySavedLanguage();
    }
});

// 1. Робимо функцію ГЛОБАЛЬНОЮ, щоб HTML її бачив
window.showTopic = function(topicId, btnElement) {
    // Знімаємо класи за замовчуванням
    document.querySelectorAll('.topic-btn').forEach(btn => btn.classList.remove('active'));
    document.querySelectorAll('.topic-content').forEach(content => content.classList.remove('active'));
    
    // Робимо активною вибрану тему
    btnElement.classList.add('active');
    document.getElementById(topicId).classList.add('active');
    
    // 💾 Зберігаємо вибір у пам'ять браузера
    localStorage.setItem('activeGrammarTopic', topicId);
    
    // Плавний скрол на мобільних
    if(window.innerWidth < 900) {
        document.querySelector('.content-area').scrollIntoView({ behavior: 'smooth' });
    }
};

// 2. Відновлюємо збережену тему при оновленні сторінки
window.addEventListener('DOMContentLoaded', () => {
    const savedTopic = localStorage.getItem('activeGrammarTopic');
    
    if (savedTopic) {
        const targetContent = document.getElementById(savedTopic);
        // Шукаємо кнопку, яка має в onclick потрібний id (враховуємо і одинарні, і подвійні лапки)
        const targetBtn = document.querySelector(`button[onclick*="'${savedTopic}'"]`) || document.querySelector(`button[onclick*='"${savedTopic}"']`);
        
        if (targetBtn && targetContent) {
            // Приховуємо все
            document.querySelectorAll('.topic-btn').forEach(btn => btn.classList.remove('active'));
            document.querySelectorAll('.topic-content').forEach(content => content.classList.remove('active'));
            
            // Показуємо тільки збережену тему
            targetBtn.classList.add('active');
            targetContent.classList.add('active');
        }
    }
});